version: "3.4"

services:
  devnet_wasp:
    image: alps86/wasp:v0.2.3
    container_name: devnet_wasp
    volumes:
      - wasp-db:/wasp/waspdb
      - ./wasp.config.json:/etc/wasp_config.json
    expose:
      - "4000/udp" # Peering
      - "5550/tcp" # Nano MSG
      - "7000/tcp" # Wasp Dashboard
      - "9090/tcp" # Wasp WebAPI
    ports:
      - "127.0.0.1:4000:4000/tcp" # Peering
      - "127.0.0.1:5550:5550/tcp" # Nano MSG
      - "127.0.0.1:7000:7000/tcp" # Wasp Dashboard
      - "127.0.0.1:9090:9090/tcp" # Wasp WebAPI

volumes:
  goshimmer-db:
    name: goshimmer-db
  wasp-db:
    name: wasp-db
