// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package sc

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "sc"
	ScDescription = "sc description"
	HScName       = wasmlib.ScHname(0x210c291a)
)

const (
	ParamOwner = "owner"
)

const (
	ResultOwner = "owner"
)

const (
	StateOwner = "owner"
)

const (
	FuncInit     = "init"
	FuncSetOwner = "setOwner"
	ViewGetOwner = "getOwner"
)

const (
	HFuncInit     = wasmlib.ScHname(0x1f44d644)
	HFuncSetOwner = wasmlib.ScHname(0x2a15fe7b)
	HViewGetOwner = wasmlib.ScHname(0x137107a6)
)
