// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

//nolint:gocritic
package sc

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type scEvents struct {
}

func (e scEvents) Bet(address wasmlib.ScAddress, amount int64, number int64) {
	wasmlib.NewEventEncoder("sc.bet").
		Address(address).
		Int64(amount).
		Int64(number).
		Emit()
}
