// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package sc

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ImmutablescState struct {
	id int32
}

func (s ImmutablescState) Counter() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxStateCounter])
}

func (s ImmutablescState) NumRepeats() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxStateNumRepeats])
}

type MutablescState struct {
	id int32
}

func (s MutablescState) Counter() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxStateCounter])
}

func (s MutablescState) NumRepeats() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxStateNumRepeats])
}
