// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "./wasmlib"
import * as events from "./events"
import * as service from "./service"

let scService: service.ScService;

export function subscribeToscEvents(): void {

	scService.on('sc_increment', (event: events.EventIncrement) => {
	});
}
