// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "./wasmlib"
import * as service from "./service"


export interface EventBet {
  timestamp: wasmlib.Int32;
  address: wasmlib.Address;
  amount: wasmlib.Int64;
  number: wasmlib.Int64;
}

export interface scEvents {
	sc_bet: (event: EventBet) => void;
}

export function handleVmMessage(message: string[]): void {
    const messageHandlers: wasmlib.MessageHandlers = {
		'sc.bet': (index) => {
			const evt: EventBet = {
				timestamp: Number(message[++index]),
				address: message[++index],
				amount: BigInt(message[++index]),
				number: BigInt(message[++index]),
			};
			this.emitter.emit('sc_bet', evt);
		},
    };

    const topicIndex = 3;
    const topic = message[topicIndex];

    if (typeof messageHandlers[topic] != 'undefined') {
      messageHandlers[topic](topicIndex);
    }
}
