// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

//go:build wasm
// +build wasm

package main

import "github.com/iotaledger/wasp/packages/vm/wasmclient"

import "test/sc/go/sc"

func main() {
}

//export on_load
func onLoad() {
	h := &wasmclient.WasmVMHost{}
	h.ConnectWasmHost()
	sc.OnLoad()
}
